import React from 'react'
export const text = (
    <>
        Lorem ipsum dolor sit amet consectetur. Turpis dictum suspendisse pellentesque pretium cras morbi in enim nisl. Morbi malesuada sit pellentesque tempor. Sagittis sed quis dui ipsum odio maecenas. Vel integer amet commodo turpis pulvinar risus odio volutpat mi. Massa faucibus sodales pretium volutpat aliquet interdum in. Sagittis elementum malesuada dui felis suspendisse penatibus sodales egestas lobortis. Accumsan felis risus nulla faucibus diam fringilla. <br />


Praesent amet nisi id sit ullamcorper lectus. Arcu porttitor nulla facilisis molestie augue. Enim urna id sit tortor. Amet fermentum consectetur id tortor. Nec consequat feugiat sed volutpat sagittis leo nunc fermentum.
Nulla sit mattis egestas eu vestibulum habitant viverra sagittis eget. Leo amet ut fermentum hendrerit dignissim facilisi. Tortor dui eget magna nisl consequat malesuada sit mauris. Ut ultrices cursus feugiat sapien. Libero faucibus id viverra at lectus. Ac purus augue molestie congue amet dignissim ac varius ridiculus. Cras libero rhoncus amet elementum neque mauris risus amet. Duis sagittis arcu sed nulla mauris. Aliquam netus et consectetur velit elementum dui tellus arcu. Convallis eget consequat maecenas maecenas elementum tristique vestibulum nisi risus. Et elementum diam ut sapien vel consequat.
Mattis nunc id nunc mattis bibendum diam. In fringilla est ullamcorper eu tempus. Arcu ornare netus sed eu accumsan. Pretium nunc magna urna tincidunt dictum risus. Commodo egestas velit amet porttitor urna. Lacus sagittis cursus augue suscipit. Arcu leo sit sem scelerisque commodo tellus ut tellus. In tincidunt nunc quis enim aliquet at felis. Quis massa pretium fermentum vel nulla molestie eleifend non risus. Donec id malesuada lorem malesuada velit. Ut massa lobortis et vel placerat. Amet condimentum eu bibendum laoreet id vel commodo phasellus purus. Accumsan massa morbi sit scelerisque molestie venenatis. Nec magna molestie nunc tortor mollis morbi ultricies.<br />


Id commodo auctor sed arcu facilisi metus. Urna elementum aenean lorem sit et viverra. Lacus phasellus odio aliquam vel mi egestas vulputate enim quis. Netus cras sed at rhoncus donec praesent. Et odio ac ultrices lectus. Sodales ultrices dolor et orci lorem. Leo egestas viverra eu orci purus. Viverra pharetra ac enim nulla metus. Volutpat tellus ac dictumst ornare sodales vel eu. Pellentesque purus id in eu risus dolor. Maecenas mi gravida ullamcorper arcu eget semper pulvinar auctor. Consectetur habitant nulla consequat sapien morbi magnis enim elementum. Congue pretium morbi neque metus mauris quam. Integer pellentesque accumsan curabitur condimentum sit enim sagittis feugiat velit.
Cursus facilisis fringilla ipsum viverra consectetur. Porttitor amet adipiscing pretium nisi mattis. Faucibus facilisi aliquet in tempus mattis faucibus curabitur. A vel libero aenean morbi hendrerit sed. Ac lacus vulputate eget gravida egestas volutpat nulla consequat.
Aliquam enim at sit ut id condimentum viverra et. Egestas pretium in ornare ornare orci arcu netus sociis gravida. Risus elementum diam gravida hendrerit quis porttitor. Libero auctor egestas nisi nisl integer. Interdum sollicitudin quam venenatis arcu habitant tincidunt.<br />


Lacinia diam ac quam nibh. A erat nisi nulla eget ornare. At nisi ac aliquam sit scelerisque. Pellentesque imperdiet pellentesque ultrices et. Quis nulla blandit aliquam lectus non consectetur at nam lorem. Adipiscing laoreet ipsum sit enim leo condimentum a et. Faucibus vitae feugiat sagittis eget euismod lacus eget cursus. Eget massa sed lobortis fringilla dapibus tristique vitae. Nunc posuere sit donec nisi adipiscing fermentum quis mi. Et tristique elit dictumst eget interdum. Mattis phasellus vel convallis egestas porttitor non neque vitae phasellus. Vitae et in pretium ut.
Consequat nec euismod arcu adipiscing risus ac. Hendrerit eu in dictum neque rhoncus turpis consectetur. Eu sit eu facilisis dolor leo fermentum lacus tincidunt. Vitae sodales etiam aenean sed quis sociis interdum. Vitae lorem lorem id sem. Quam integer neque nisl enim ut nec scelerisque. Morbi pharetra et commodo mattis proin. Interdum purus at at venenatis rhoncus velit arcu aliquet lectus. Vitae phasellus gravida enim sit cras a mauris sed morbi. Adipiscing nam nisl nibh id gravida venenatis ultricies non diam. <br />


Nam morbi at imperdiet mi. Diam posuere ridiculus pharetra vel augue egestas eget felis interdum. Nullam turpis elementum bibendum massa ridiculus sagittis non morbi non. Commodo blandit quis egestas pellentesque vitae et. Sit quam in sit tortor. Tincidunt nibh quis gravida sit hendrerit tellus maecenas sit odio. Consectetur curabitur cursus facilisi sed senectus feugiat. Suspendisse egestas tellus cursus tempus a arcu ut maecenas pellentesque. Ut lectus cursus cursus sed.
Amet habitasse at proin suspendisse sed sit in. Et ridiculus tristique ut leo nec et tincidunt. Aliquam nulla diam nunc nunc scelerisque suspendisse cursus ultrices viverra. A id in pellentesque sit lorem. Eu libero pretium pharetra tempor convallis ultricies. Morbi risus varius leo sit morbi arcu egestas eu amet. Vel amet aliquet sapien rutrum. Enim faucibus dis est at porttitor at odio porta. Feugiat habitasse nunc quis mi.
Ut porttitor sit faucibus rutrum risus. Id scelerisque lacinia vulputate ultricies sed enim. Pharetra cras viverra gravida tortor ultrices dictum. Faucibus augue eget turpis ac tellus sed ut libero. Mattis cras lacinia quis sit urna tempus viverra a velit. Risus ultricies proin lacus in amet. Habitant nam sed commodo ultrices sed eget blandit est laoreet. Quisque ultrices risus varius a sed. In nec in viverra purus. Purus neque nunc potenti tellus. Et ipsum mattis scelerisque volutpat sed risus.
Integer mi at nisl ultricies consequat nunc. Ullamcorper sit sed tempor adipiscing laoreet sem eleifend. Ipsum odio aliquet nunc volutpat. Nisl egestas enim enim nec turpis cursus. Nunc urna dictum consectetur egestas neque senectus aliquam egestas.
In elit duis odio consectetur ut. Iaculis sit sed vitae id vel ultricies sed fringilla et. Non dui integer sit integer. Sed integer arcu ut risus justo adipiscing. Ipsum vulputate non semper quis enim quis sed donec sed. Enim ut viverra turpis consectetur pharetra convallis. Massa diam hac dolor euismod venenatis. Venenatis tellus vitae viverra diam at morbi. Bibendum eget tincidunt commodo enim imperdiet ac etiam orci porta. Augue nunc maecenas vitae ac scelerisque est massa. Justo porttitor tristique neque convallis quisque vitae. Fermentum lectus volutpat felis gravida non justo feugiat at nulla. Nunc scelerisque cursus aenean turpis vel nulla aliquam nibh. Ut faucibus sapien vulputate ornare sed donec purus fermentum arcu. Ut egestas lobortis varius non.
Dignissim rhoncus scelerisque interdum gravida eget eget eget nisl. Lacus mattis ultrices at lacus pharetra id. Vitae condimentum mattis semper phasellus ipsum. Amet velit lorem cursus lacus ultrices suscipit ac aliquet. Risus diam quisque id dignissim lobortis morbi interdum mauris amet. Scelerisque augue vel venenatis amet. Nulla urna quam fermentum iaculis quam facilisis consequat diam vel.<br/>


Malesuada id cras praesent nisi morbi magna vestibulum augue. Magnis egestas in tincidunt curabitur arcu netus ipsum sed. Urna nunc dis orci dui consequat. Lobortis sit amet morbi feugiat. Purus amet mattis tincidunt ultrices augue amet convallis. Tortor massa elementum pellentesque aliquam et et. Mi dui parturient urna feugiat non rutrum eros purus.
Velit malesuada ridiculus ultricies viverra. Lorem feugiat orci massa tempus nulla cursus venenatis. Tempor lacus magna in in dolor. Tempus elementum sit sit mollis libero ut augue mi malesuada. Egestas ac vel elit non nunc convallis ipsum. Porttitor mi quis massa sed vitae faucibus interdum at elit. Nisl aliquam venenatis sed egestas eu facilisis. Dictum cursus ipsum adipiscing elementum. Auctor adipiscing nisi aliquam ornare amet. Donec volutpat blandit risus arcu sagittis vitae congue. Gravida nunc nunc velit sollicitudin suspendisse eu morbi. Volutpat sagittis egestas sed leo commodo. Consequat molestie sit ut enim egestas commodo fringilla massa cum.
Mi aliquam consectetur tincidunt faucibus odio. Tempor ipsum diam imperdiet tristique in. Id sagittis maecenas enim facilisi. Adipiscing risus sit nec ornare sollicitudin nunc vulputate. Quisque malesuada ornare elementum tortor est. Integer senectus auctor ac platea. Donec ultricies duis ipsum tellus. Turpis libero tincidunt integer quam. Sit neque arcu amet malesuada elit tincidunt. Sit lacus elit sit ut.
In cursus tortor massa in enim facilisis tellus consectetur habitasse. Diam ligula amet neque pellentesque at tincidunt morbi. Mauris tincidunt sed eu sodales nunc ipsum massa. Diam erat egestas nulla pharetra sed volutpat. Lectus adipiscing quis consequat faucibus eget tortor. A eu cursus neque placerat habitant scelerisque. Lobortis elementum tincidunt rhoncus arcu cras egestas duis in augue. Ligula aliquet et massa at. Felis quisque mi sagittis vitae. Nam ornare sed sit aliquet. Hendrerit volutpat in varius pulvinar arcu. Sed diam ridiculus phasellus ullamcorper pulvinar curabitur malesuada nulla gravida. Faucibus velit sodales sapien proin odio tellus porttitor.
    </>
)